import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import SupabaseProvider from './supabase-provider';
import classNames from "classnames";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={classNames(inter.className, 'bg-black text-secondary')}>
    <SupabaseProvider>
      {children}
    </SupabaseProvider>
    </body>
    </html>
  );
}
